print("-----------Enter Information Details-----------")
fname = input("Enter First Name: ")
mname = input("Enter Middle Name: ")
lname = input("Enter Last Name: ")
bday = input("Enter Birthday (MM/DD/YYYY): ")
gender = input("Enter Gender (M/F): ")
address = input("Enter Address: ")
course = input("Enter Course: ")
yrlevel = input("Enter Year Level: ")

print("\n----------------INFORMATION----------------")
print("Name:",fname,mname,lname)
print("Birthday:",bday)
print("Gender:",gender)
print("Address:",address)
print("Course:",course)
print("Year Level:",yrlevel)